// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main #(
 parameter v72d645 = 1111_1111,
 parameter vbea385 = 255,
 parameter vd9e95e = 0xFF
) (
 input v0020d1,
 input ve3e833,
 input [1:0] vc9ba64,
 output v05b20f,
 output v4f4e7e,
 output v549f54,
 output v089eb5,
 output v485c0b,
 output vdc8346,
 output va400e7,
 output v65d3c2,
 output [7:0] v09b76e,
 output v0eb437,
 output v932add,
 output [1:0] v19c807
);
 localparam p0 = v72d645;
 wire w1;
 wire w2;
 wire w3;
 wire [0:1] w4;
 wire w5;
 wire w6;
 wire [0:1] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire [0:7] w16;
 assign v0eb437 = w1;
 assign w2 = ve3e833;
 assign w3 = ve3e833;
 assign v932add = w3;
 assign w4 = vc9ba64;
 assign v19c807 = w7;
 assign w8 = v0020d1;
 assign v05b20f = w8;
 assign w9 = v0020d1;
 assign v4f4e7e = w9;
 assign w10 = v0020d1;
 assign v089eb5 = w10;
 assign w11 = v0020d1;
 assign v549f54 = w11;
 assign w12 = v0020d1;
 assign va400e7 = w12;
 assign w13 = v0020d1;
 assign v485c0b = w13;
 assign w14 = v0020d1;
 assign vdc8346 = w14;
 assign w15 = v0020d1;
 assign v65d3c2 = w15;
 assign v09b76e = w16;
 assign w3 = w2;
 assign w9 = w8;
 assign w10 = w8;
 assign w10 = w9;
 assign w11 = w8;
 assign w11 = w9;
 assign w11 = w10;
 assign w12 = w8;
 assign w12 = w9;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w8;
 assign w13 = w9;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w14 = w8;
 assign w14 = w9;
 assign w14 = w10;
 assign w14 = w11;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w8;
 assign w15 = w9;
 assign w15 = w10;
 assign w15 = w11;
 assign w15 = w12;
 assign w15 = w13;
 assign w15 = w14;
 vffc517 #(
  .vc5c8ea(p0)
 ) v536cb1 (
  .va0aeac(w16)
 );
 v3676a0 v365a52 (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 v0dbcb9 vd061ac (
  .v8b19dd(w4),
  .v3f8943(w5),
  .v64d863(w6)
 );
 v80ac84 ve1b39d (
  .vee8a83(w5),
  .v03aaf0(w6),
  .v67a3fc(w7)
 );
endmodule

//---- Top entity
module vffc517 #(
 parameter vc5c8ea = 0
) (
 output [7:0] va0aeac
);
 localparam p0 = vc5c8ea;
 wire [0:7] w1;
 assign va0aeac = w1;
 vffc517_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 8-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 8-bits generic constant (0-255)
//---------------------------------------------------

module vffc517_v465065 #(
 parameter VALUE = 0
) (
 output [7:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module v0dbcb9 (
 input [1:0] v8b19dd,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = v8b19dd;
 v0dbcb9_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus2-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus2-Split-all: Split the 2-bits bus into two wires
//---------------------------------------------------

module v0dbcb9_v9a2a06 (
 input [1:0] i,
 output o1,
 output o0
);
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v80ac84 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 v80ac84_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

//---------------------------------------------------
//-- Bus2-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus2-Join-all: Joint two wires into a 2-bits Bus
//---------------------------------------------------

module v80ac84_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
