// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main (
 output v8f8964,
 output v6d1e30,
 output v106aba,
 output [0:4] vinit
);
 wire w0;
 wire w1;
 wire w2;
 assign v8f8964 = w0;
 assign v6d1e30 = w1;
 assign v106aba = w2;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 vfebcfe vfd7d62 (
  .v9fb85f(w0)
 );
 assign vinit = 5'b00000;
endmodule

//---------------------------------------------------
//-- Led on
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
